version: '3.4'

services:
  aggregator-fe:
    image: sampleproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
